name: C/C++ CI

on:
  push:
    branches:
      - master
      - actions #temp

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: apt update && apt install clang
    - name: Build
      run: clang fixts.c -o fixts.c -o fixts
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: fixts
        path: fixts
